name: marshmallow
description: Object Detection Game

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  introduction_screen: ^2.1.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bordered_text: ^2.0.0
  get: ^4.3.8
  animated_splash_screen: ^1.1.0
  cloud_firestore: ^2.5.4
  firebase_core: ^1.8.0
  firebase_auth: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/avatars/


  fonts:
    - family: Point
      fonts:
        - asset: fonts/Modak-Regular.ttf
  
    - family: Main
      fonts:
        - asset: fonts/NanumGothic-ExtraBold.ttf
        - asset: fonts/NanumGothic-Bold.ttf
        - asset: fonts/NanumGothic-Regular.ttf
      