List avatarRepository = [
  "assets/avatars/bear.png",
  "assets/avatars/cat.png",
  "assets/avatars/dog.png",
  "assets/avatars/hamster.png",
  "assets/avatars/koala.png",
  "assets/avatars/monkey.png",
  "assets/avatars/panda.png",
  "assets/avatars/rabbit.png",
  "assets/avatars/tiger.png",
];

List<String> wordRepository = [
  "goldfish",
  "cock",
  "ostrich",
  "bulbul",
  "magpie",
  "kite",
  "bald eagle",
  "scorpion",
  "axolotl",
  "flamingo",
  "triceratops",
  "Indian cobra",
  "centipede",
  "goose",
  "jellyfish",
  "snail",
  "pelican",
  "killer whale",
  "zebra",
  "church",
  "coffeepot",
  "crane",
  "digital clock",
  "golden retriever",
  "standard poodle",
  "Maltese dog",
  "Shih-Tzu",
  "Persian cat",
  "dumbbell",
  "electric guitar",
  "espresso maker",
  "fire screen",
  "fountain",
  "golf ball",
  "grand piano",
  "hand blower",
  "beagle",
  "microphone",
  "military uniform",
  "monitor",
  "mountain bike",
  "sunglasses",
  "table lamp",
  "violin",
  "traffic light",
  "strawberry",
  "pineapple",
  "pizza",
  "toilet tissue",
  "analog clock",
];
